/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyCockpitEnvironmentTable {
        "environmentData": {
    nome: string;
    versao: string;
    dependenciasInstaladas: {
      nome: string;
      versao: string;
      pacote: string;
      atualizacaoDisponivel: boolean | null;
      status: string;
    }[];
  };
        "firstEnv": boolean | null;
    }
    interface SyCockpitEnvironmentsTable {
    }
    interface SyCockpitExample {
    }
    interface SyCockpitRootContainer {
    }
    interface SyCockpitVersionTag {
    }
}
declare global {
    interface HTMLSyCockpitEnvironmentTableElement extends Components.SyCockpitEnvironmentTable, HTMLStencilElement {
    }
    var HTMLSyCockpitEnvironmentTableElement: {
        prototype: HTMLSyCockpitEnvironmentTableElement;
        new (): HTMLSyCockpitEnvironmentTableElement;
    };
    interface HTMLSyCockpitEnvironmentsTableElement extends Components.SyCockpitEnvironmentsTable, HTMLStencilElement {
    }
    var HTMLSyCockpitEnvironmentsTableElement: {
        prototype: HTMLSyCockpitEnvironmentsTableElement;
        new (): HTMLSyCockpitEnvironmentsTableElement;
    };
    interface HTMLSyCockpitExampleElement extends Components.SyCockpitExample, HTMLStencilElement {
    }
    var HTMLSyCockpitExampleElement: {
        prototype: HTMLSyCockpitExampleElement;
        new (): HTMLSyCockpitExampleElement;
    };
    interface HTMLSyCockpitRootContainerElement extends Components.SyCockpitRootContainer, HTMLStencilElement {
    }
    var HTMLSyCockpitRootContainerElement: {
        prototype: HTMLSyCockpitRootContainerElement;
        new (): HTMLSyCockpitRootContainerElement;
    };
    interface HTMLSyCockpitVersionTagElement extends Components.SyCockpitVersionTag, HTMLStencilElement {
    }
    var HTMLSyCockpitVersionTagElement: {
        prototype: HTMLSyCockpitVersionTagElement;
        new (): HTMLSyCockpitVersionTagElement;
    };
    interface HTMLElementTagNameMap {
        "sy-cockpit-environment-table": HTMLSyCockpitEnvironmentTableElement;
        "sy-cockpit-environments-table": HTMLSyCockpitEnvironmentsTableElement;
        "sy-cockpit-example": HTMLSyCockpitExampleElement;
        "sy-cockpit-root-container": HTMLSyCockpitRootContainerElement;
        "sy-cockpit-version-tag": HTMLSyCockpitVersionTagElement;
    }
}
declare namespace LocalJSX {
    interface SyCockpitEnvironmentTable {
        "environmentData"?: {
    nome: string;
    versao: string;
    dependenciasInstaladas: {
      nome: string;
      versao: string;
      pacote: string;
      atualizacaoDisponivel: boolean | null;
      status: string;
    }[];
  };
        "firstEnv"?: boolean | null;
    }
    interface SyCockpitEnvironmentsTable {
    }
    interface SyCockpitExample {
    }
    interface SyCockpitRootContainer {
    }
    interface SyCockpitVersionTag {
    }
    interface IntrinsicElements {
        "sy-cockpit-environment-table": SyCockpitEnvironmentTable;
        "sy-cockpit-environments-table": SyCockpitEnvironmentsTable;
        "sy-cockpit-example": SyCockpitExample;
        "sy-cockpit-root-container": SyCockpitRootContainer;
        "sy-cockpit-version-tag": SyCockpitVersionTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-cockpit-environment-table": LocalJSX.SyCockpitEnvironmentTable & JSXBase.HTMLAttributes<HTMLSyCockpitEnvironmentTableElement>;
            "sy-cockpit-environments-table": LocalJSX.SyCockpitEnvironmentsTable & JSXBase.HTMLAttributes<HTMLSyCockpitEnvironmentsTableElement>;
            "sy-cockpit-example": LocalJSX.SyCockpitExample & JSXBase.HTMLAttributes<HTMLSyCockpitExampleElement>;
            "sy-cockpit-root-container": LocalJSX.SyCockpitRootContainer & JSXBase.HTMLAttributes<HTMLSyCockpitRootContainerElement>;
            "sy-cockpit-version-tag": LocalJSX.SyCockpitVersionTag & JSXBase.HTMLAttributes<HTMLSyCockpitVersionTagElement>;
        }
    }
}
